//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpVictorAngDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DescuentoCliente
    {
        public long IdDescuentoCliente { get; set; }
        public long IdCliente { get; set; }
        public long IdDescuento { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Descuento Descuento { get; set; }
    }
}
